apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: {{ .Values.ingress.name }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.front.name }}
            port: 
              number: 80
      - path: /api
        pathType: Exact
        backend:
          service:
            name: {{ .Values.service.back.name }}
            port: 
              number: 80