apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: 
        - /bin/sh
        - -c
        - |
          while true; do
            echo "$(date +'%Y-%m-%d %H:%M:%S') Test from busybox" >> /output/log.txt
            sleep 5
          done
        volumeMounts:
        - name: shared-volume
          mountPath: /output

      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: shared-volume
          mountPath: /shared-volume
        ports:
        - containerPort: 80

      volumes:
      - name: shared-volume
        hostPath:
          path: /tmp/share
