apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      name: multitool-daemonset
  template:
    metadata:
      labels:
        name: multitool-daemonset
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log

      volumes:
      - name: varlog
        hostPath:
          path: /var/log
