apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-app
  name: my-app-pod
  namespace: default
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool:openshift
    imagePullPolicy: IfNotPresent
    env:
    - name: HTTP_PORT
      value: "8080"
