apiVersion: v1
kind: Service
metadata:
  name: my-app-service-nodeport
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
      nodePort: 30001
    - name: multitool
      port: 9002
      targetPort: 8080
      nodePort: 30002