apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: pvc-storage
  namespace: default
spec:
  storageClassName: manual
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi