apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 80
    - name: https
      port: 8000
      targetPort: 443