apiVersion: v1
kind: PersistentVolume 
metadata:
  name: pv-homework 
spec:
  capacity: 
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/hw
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - k8s