apiVersion: v1
kind: PersistentVolume 
metadata:
  name: pv-homework 
spec:
  capacity: 
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/hw
  persistentVolumeReclaimPolicy: Retain