deployment:
  front:
    name: frontend
    replicas: 2
    image: kirskirill/custom-nginx
    tag: 1.0.0
    containerPort: 80
    labels:
      app: frontend
  back:
    name: backend
    replicas: 2
    image: wbitt/network-multitool
    tag: latest
    containerPort: 80
    labels:
      app: backend

service:
  front:
    name: frontend-service
    selector: frontend
    ports:
      port: 9001
      targetPort: 80
  back:
    name: backend-service
    selector: backend
    ports:
      port: 9002
      targetPort: 80

ingress:
  name: ingress
  host: k8s.test