deployment:
  front:
    name: frontend
    replicas: 2
    image: nginx
    tag: 1
    containerPort: 80
    labels:
      app: frontend

service:
  front:
    name: frontend-service
    selector: frontend
    ports:
      port: 9001
      targetPort: 80
