apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels: 
        app: my-app
    spec:
      volumes:
      - name: cm-volume   
        configMap:  # подключаем configMap как volume
          name: my-app-cm # имя configMap
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts: # монтируем volume с configMap
        - name: cm-volume
          mountPath: /usr/share/nginx/html
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:  # передаем env  из configMap
              name: my-app-cm
              key: HTTP_PORT
