[webservers]
web-1   ansible_host=89.169.135.86 fqdn=hw-03-1.ru-central1.internal
web-2   ansible_host=51.250.68.167 fqdn=hw-03-2.ru-central1.internal

[databases]
main   ansible_host=89.169.129.201 fqdn=main.ru-central1.internal
replica   ansible_host=51.250.7.75 fqdn=replica.ru-central1.internal

[storage]
storage   ansible_host=89.169.148.243 fqdn=storage.ru-central1.internal